preload = /home/skydogzz/.config/hypr/wallpapers/anime-girl.png

wallpaper = eDP-2,/home/skydogzz/.config/hypr/wallpapers/anime-girl.png,fill
wallpaper = DP-4,/home/skydogzz/.config/hypr/wallpapers/anime-girl.png,fill
