general {
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
    lock_cmd = hyprlock
}

listener {
    timeout = 120
    on-timeout = brightnessctl -s set 5%
}

listener {
    timeout = 180
    on-timeout = hyprlock
}

listener {
    timeout = 210
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}
