# ── float oning windows ──
windowrule = match:class ^(org\.twosheds\.iwgtk|iwgtk)$, float on
windowrule = match:class ^(org\.twosheds\.iwgtk|iwgtk)$, center on
windowrule = match:class ^(blueberry\.py|Blueberry\.py)$, float on
windowrule = match:class ^(blueberry\.py|Blueberry\.py)$, center on
windowrule = match:initial_class ^(pavucontrol|Pavucontrol|org\.pulseaudio\.pavucontrol)$, float on, center on, size 1200 700
windowrule = match:class ^(xdg-desktop-portal)$, float on
windowrule = match:class ^(wlogout)$, float on
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:title ^(Picture-in-Picture)$, center on
windowrule = match:title ^(Picture-in-Picture)$, pin on

# ── Appearance ──
windowrule = match:class ^(waybar)$, no_blur on
windowrule = match:class ^(rofi)$, no_blur on
windowrule = match:fullscreen 1, border_size 0
