preload = /home/skydogzz/.config/hypr/wallpapers/Anime Girl Wallpaper.jpeg

wallpaper {
    monitor = eDP-2
    path = /home/skydogzz/.config/hypr/wallpapers/Anime Girl Wallpaper.jpeg
    fit_mode = fill
}
