color_theme = "catppuccin_mocha"
theme_background = false
truecolor = true
force_tty = false
preserve_aspect_ratio = false

# Layout
box_border = "rounded"
shown_boxes = "proc cpu mem net"
graph_symbol = "default"

# Update
update_ms = 2000
